import type { StyleId, StyleType } from './types'

export const STYLE_TYPES: Record<StyleId, StyleType> = {
  COSMIC_REBEL: {
    id: 'COSMIC_REBEL',
    name: 'Cosmic Rebel',
    subtitle: '宇宙的反逆者',
    description: '既成概念を打ち壊し、宇宙のスケールで自分を表現する。ルールに縛られず、ファッションを自己革命のツールとして使う。あなたの存在自体がアート。',
    traits: ['前衛的', '実験的', 'カリスマ性', '独創的'],
    keywords: ['アバンギャルド', 'SF', 'メタリック', 'レイヤード', 'ユニセックス'],
    palette: ['#7C3AED', '#EC4899', '#000000', '#C0C0C0'],
    emoji: '🚀',
    gradient: 'linear-gradient(135deg, #7C3AED 0%, #EC4899 50%, #000000 100%)',
  },
  SOFT_DREAMER: {
    id: 'SOFT_DREAMER',
    name: 'Soft Dreamer',
    subtitle: '柔らかな夢想家',
    description: '淡い色彩と柔らかな素材で包まれた、夢の中にいるような世界観。繊細さと優しさを纏い、見る人をふんわりとした世界へ誘う。',
    traits: ['繊細', '優しい', 'ロマンティック', '直感的'],
    keywords: ['パステル', 'シフォン', 'フリル', 'フローラル', 'レース'],
    palette: ['#FBCFE8', '#E9D5FF', '#FEF3C7', '#FFFFFF'],
    emoji: '🌸',
    gradient: 'linear-gradient(135deg, #FBCFE8 0%, #E9D5FF 50%, #BAE6FD 100%)',
  },
  URBAN_EDGE: {
    id: 'URBAN_EDGE',
    name: 'Urban Edge',
    subtitle: '都市の先駆者',
    description: '街を舞台にしたストリートカルチャーを纏う、トレンドの最前線を走る存在。スポーツとファッションの境界を曖昧にし、都市のエネルギーを体現する。',
    traits: ['クール', 'トレンド敏感', 'エネルギッシュ', '自信家'],
    keywords: ['スニーカー', 'オーバーサイズ', 'グラフィック', 'ストリート', 'スポーティ'],
    palette: ['#1F2937', '#FFFFFF', '#EF4444', '#F59E0B'],
    emoji: '🏙️',
    gradient: 'linear-gradient(135deg, #1F2937 0%, #374151 50%, #6B7280 100%)',
  },
  CLASSIC_ELITE: {
    id: 'CLASSIC_ELITE',
    name: 'Classic Elite',
    subtitle: '永遠のエレガンス',
    description: '時代を超えた美意識と品格を持ち、クラシックなラグジュアリーを体現する。流行に左右されない確固たるスタイルで、周囲に存在感を放つ。',
    traits: ['洗練', '品格', '几帳面', '美意識が高い'],
    keywords: ['テーラード', 'カシミア', 'パール', 'ネイビー', 'ベージュ'],
    palette: ['#1E1B4B', '#F5F5DC', '#C4A882', '#2D3748'],
    emoji: '👑',
    gradient: 'linear-gradient(135deg, #1E1B4B 0%, #4C1D95 50%, #C4A882 100%)',
  },
  FREE_SPIRIT: {
    id: 'FREE_SPIRIT',
    name: 'Free Spirit',
    subtitle: '自由な魂',
    description: 'ボヘミアンな精神で大地と繋がり、自然の美しさを纏う。型にはまらない自由さと、アースカラーの温もりが混ざり合った独自のワールドを作り出す。',
    traits: ['自由奔放', '自然愛好', 'クリエイティブ', '包容力'],
    keywords: ['ボヘミアン', 'マクラメ', 'アースカラー', 'フロー', 'ハンドメイド'],
    palette: ['#92400E', '#D97706', '#6B7280', '#ECFDF5'],
    emoji: '🌿',
    gradient: 'linear-gradient(135deg, #92400E 0%, #D97706 50%, #6B7280 100%)',
  },
  DARK_POET: {
    id: 'DARK_POET',
    name: 'Dark Poet',
    subtitle: '闇の詩人',
    description: '深みのある闇の中に美を見出し、ゴシックとロマンティシズムを融合させる。内なる世界の豊かさを、黒と深紅で語りかける孤高の芸術家。',
    traits: ['内省的', '芸術的', '神秘的', '感受性が強い'],
    keywords: ['ゴシック', 'ベルベット', 'レース', 'ブラック', 'クロス'],
    palette: ['#000000', '#7F1D1D', '#4C1D95', '#1F2937'],
    emoji: '🖤',
    gradient: 'linear-gradient(135deg, #000000 0%, #7F1D1D 50%, #4C1D95 100%)',
  },
  RETRO_WAVE: {
    id: 'RETRO_WAVE',
    name: 'Retro Wave',
    subtitle: 'ノスタルジックな波',
    description: '70s〜90sのポップカルチャーへのオマージュを纏う、カラフルなノスタルジア。過去と現在を繋ぎ、ヴィンテージのエッセンスを現代に再解釈する。',
    traits: ['遊び心', '懐古主義', '陽気', 'コレクター気質'],
    keywords: ['ヴィンテージ', 'デニム', 'チェック', 'レトロカラー', 'Y2K'],
    palette: ['#F472B6', '#FBBF24', '#34D399', '#60A5FA'],
    emoji: '📼',
    gradient: 'linear-gradient(135deg, #F472B6 0%, #FBBF24 50%, #34D399 100%)',
  },
  MINIMAL_SOUL: {
    id: 'MINIMAL_SOUL',
    name: 'Minimal Soul',
    subtitle: 'ミニマルな魂',
    description: '余計なものを削ぎ落とし、本質だけを纏う。シンプルの中に宿る深い美意識と、素材・シルエットへのこだわりで語る、静かな主張。',
    traits: ['ミニマリスト', '完璧主義', '質重視', '静かな自信'],
    keywords: ['モノトーン', 'シルエット', '素材感', 'クリーン', 'タイムレス'],
    palette: ['#FFFFFF', '#F3F4F6', '#6B7280', '#111827'],
    emoji: '◽',
    gradient: 'linear-gradient(135deg, #F9FAFB 0%, #E5E7EB 50%, #374151 100%)',
  },
}
