import type { StyleId } from '@/lib/style-id/types'
import type { BodyType } from '@/lib/styleAdvice'

export type AffiliateItem = {
  id: string
  itemName: string
  category: string
  reason: string
  point: string
  tags: string[]
  imageLabel: string
  affiliateUrl: string
}

const AFFILIATE_ITEMS: Record<StyleId, Record<BodyType, AffiliateItem[]>> = {
  COSMIC_REBEL: {
    straight: [
      {
        id: 'cr-st-1',
        itemName: 'メタリックスキニーパンツ',
        category: 'ボトムス',
        reason: 'メリハリシルエットを活かした光沢素材でCOSMIC REBELらしさを体現',
        point: 'タックインでIラインを強調すると◎',
        tags: ['メタリック', 'タイト', 'シャープ'],
        imageLabel: '🌟',
        affiliateUrl: 'https://example.com/affiliate/cr-st-1',
      },
      {
        id: 'cr-st-2',
        itemName: 'ストラクチャードショルダージャケット',
        category: 'アウター',
        reason: '肩ラインをシャープに見せ、アバンギャルドな存在感を放つ',
        point: 'インナーはボディスーツでシルエットをスッキリさせると◎',
        tags: ['ストラクチャード', 'アバンギャルド', 'モード'],
        imageLabel: '🪐',
        affiliateUrl: 'https://example.com/affiliate/cr-st-2',
      },
    ],
    wave: [
      {
        id: 'cr-wv-1',
        itemName: 'フィットメタリックスカート',
        category: 'ボトムス',
        reason: '曲線美を活かしたフィット感でガーリーなSFスタイルを完成させる',
        point: 'クロップドトップスとの組み合わせでウエストを強調',
        tags: ['メタリック', 'フィット', 'フェミニン'],
        imageLabel: '✨',
        affiliateUrl: 'https://example.com/affiliate/cr-wv-1',
      },
      {
        id: 'cr-wv-2',
        itemName: 'ホルターネックボディコンワンピース',
        category: 'ワンピース',
        reason: 'カーブィなシルエットを最大限に引き立てるフィット感',
        point: 'アクセサリーはシルバー系でSF感を演出',
        tags: ['ボディコン', 'フィット', 'SF'],
        imageLabel: '🛸',
        affiliateUrl: 'https://example.com/affiliate/cr-wv-2',
      },
    ],
    natural: [
      {
        id: 'cr-nt-1',
        itemName: 'オーバーサイズレザーブルゾン',
        category: 'アウター',
        reason: 'フレーム感のある骨格にボリュームを重ねて宇宙的な存在感を放つ',
        point: 'ワイドパンツとのYラインで骨格の強さを活かす',
        tags: ['レザー', 'オーバーサイズ', 'エッジ'],
        imageLabel: '⚡',
        affiliateUrl: 'https://example.com/affiliate/cr-nt-1',
      },
      {
        id: 'cr-nt-2',
        itemName: 'レイヤードセットアップ',
        category: 'セットアップ',
        reason: '重ね着でボリュームと奥行きを演出し、骨格の強さを活かしたスタイルに',
        point: '素材感の異なるアイテムを重ねるとよりクリエイティブに',
        tags: ['レイヤード', 'セットアップ', 'ボリューム'],
        imageLabel: '🌌',
        affiliateUrl: 'https://example.com/affiliate/cr-nt-2',
      },
    ],
  },

  SOFT_DREAMER: {
    straight: [
      {
        id: 'sd-st-1',
        itemName: 'シルクサテンフィットワンピース',
        category: 'ワンピース',
        reason: 'メリハリボディに寄り添うシルクの光沢感で上品ドリーマーを演出',
        point: 'ベルトでウエストをさらに強調するとよりエレガントに',
        tags: ['シルク', 'フィット', 'エレガント'],
        imageLabel: '🌸',
        affiliateUrl: 'https://example.com/affiliate/sd-st-1',
      },
      {
        id: 'sd-st-2',
        itemName: 'テーパードシフォンパンツ',
        category: 'ボトムス',
        reason: 'きれいなIラインでドリーマーの繊細さを表現',
        point: 'トップスをタックインしてスッキリしたシルエットに',
        tags: ['シフォン', 'テーパード', 'きれいめ'],
        imageLabel: '🕊️',
        affiliateUrl: 'https://example.com/affiliate/sd-st-2',
      },
    ],
    wave: [
      {
        id: 'sd-wv-1',
        itemName: 'ティアードシフォンスカート',
        category: 'ボトムス',
        reason: '段々のフリルがウェーブの曲線美を引き立て、夢のような雰囲気に',
        point: 'フィットしたトップスでウエストのメリハリを出して',
        tags: ['シフォン', 'ティアード', 'フェミニン'],
        imageLabel: '🌷',
        affiliateUrl: 'https://example.com/affiliate/sd-wv-1',
      },
      {
        id: 'sd-wv-2',
        itemName: 'フリルブラウス',
        category: 'トップス',
        reason: 'ウェーブの柔らかさと相性抜群のフリルで最大限のフェミニンさを',
        point: 'スカートはシンプルなAラインで全体をバランス良く',
        tags: ['フリル', 'ガーリー', 'ロマンティック'],
        imageLabel: '🎀',
        affiliateUrl: 'https://example.com/affiliate/sd-wv-2',
      },
    ],
    natural: [
      {
        id: 'sd-nt-1',
        itemName: 'リネンマキシワンピース',
        category: 'ワンピース',
        reason: 'フレーム感のある骨格とリネンの自然な素材感が絶妙にマッチ',
        point: '腰にベルトをゆるく巻いてナチュラルにウエストを作ると◎',
        tags: ['リネン', 'マキシ', 'ナチュラル'],
        imageLabel: '🌿',
        affiliateUrl: 'https://example.com/affiliate/sd-nt-1',
      },
      {
        id: 'sd-nt-2',
        itemName: 'ロングカーディガン',
        category: 'アウター',
        reason: 'ゆったりとしたロング丈でフローイングなドリーマースタイルを完成',
        point: 'ワンピースやスカートの上に羽織ってレイヤードを楽しんで',
        tags: ['カーディガン', 'ロング', 'ゆったり'],
        imageLabel: '🍃',
        affiliateUrl: 'https://example.com/affiliate/sd-nt-2',
      },
    ],
  },

  URBAN_EDGE: {
    straight: [
      {
        id: 'ue-st-1',
        itemName: 'スキニーデニム',
        category: 'ボトムス',
        reason: 'メリハリボディにスリムフィットで、ストリートをシャープに攻略',
        point: 'ロールアップして足首を見せるとよりスタイリッシュに',
        tags: ['デニム', 'スキニー', 'スリム'],
        imageLabel: '👖',
        affiliateUrl: 'https://example.com/affiliate/ue-st-1',
      },
      {
        id: 'ue-st-2',
        itemName: 'クロップドグラフィックT',
        category: 'トップス',
        reason: 'コンパクトなシルエットでメリハリを活かしたストリートスタイルに',
        point: 'ハイウエストパンツとの組み合わせで脚長効果も',
        tags: ['クロップド', 'グラフィック', 'ストリート'],
        imageLabel: '🎨',
        affiliateUrl: 'https://example.com/affiliate/ue-st-2',
      },
    ],
    wave: [
      {
        id: 'ue-wv-1',
        itemName: 'オーバーサイズパーカー',
        category: 'トップス',
        reason: 'トップにボリュームを持たせてカーブィな下半身とのメリハリを演出',
        point: 'スキニーパンツやタイトスカートでバランスを取って',
        tags: ['オーバーサイズ', 'パーカー', 'カジュアル'],
        imageLabel: '🏙️',
        affiliateUrl: 'https://example.com/affiliate/ue-wv-1',
      },
      {
        id: 'ue-wv-2',
        itemName: 'バイカーショーツ',
        category: 'ボトムス',
        reason: 'ウェーブの曲線を活かしたフィット感でスポーティーかつフェミニンに',
        point: 'オーバーサイズトップスとのバランスが◎',
        tags: ['バイカー', 'スポーティー', 'フェミニン'],
        imageLabel: '⚡',
        affiliateUrl: 'https://example.com/affiliate/ue-wv-2',
      },
    ],
    natural: [
      {
        id: 'ue-nt-1',
        itemName: 'ビッグシルエットMA-1',
        category: 'アウター',
        reason: '骨格の強さを活かした圧倒的なボリューム感でストリートを支配',
        point: 'ワイドカーゴパンツと合わせてフルオーバーサイズに',
        tags: ['MA-1', 'オーバーサイズ', 'ストリート'],
        imageLabel: '🔥',
        affiliateUrl: 'https://example.com/affiliate/ue-nt-1',
      },
      {
        id: 'ue-nt-2',
        itemName: 'ワイドカーゴパンツ',
        category: 'ボトムス',
        reason: 'ゆったりとしたシルエットがナチュラル骨格のフレーム感を活かす',
        point: 'コンパクトなトップスでバランスを取るとスタイリッシュに',
        tags: ['カーゴ', 'ワイド', 'ユーティリティ'],
        imageLabel: '🎒',
        affiliateUrl: 'https://example.com/affiliate/ue-nt-2',
      },
    ],
  },

  CLASSIC_ELITE: {
    straight: [
      {
        id: 'ce-st-1',
        itemName: 'テーラードジャケット',
        category: 'アウター',
        reason: 'メリハリ体型に王道テーラードで、エリートの品格を完璧に体現',
        point: 'インナーはシンプルなシャツやタートルネックで品格を保って',
        tags: ['テーラード', 'クラシック', '品格'],
        imageLabel: '🎩',
        affiliateUrl: 'https://example.com/affiliate/ce-st-1',
      },
      {
        id: 'ce-st-2',
        itemName: 'カシミアタートルネックニット',
        category: 'トップス',
        reason: '上質な素材感がメリハリシルエットをさらに洗練させる',
        point: 'スリムパンツと合わせてIラインを完成させて',
        tags: ['カシミア', 'タートルネック', '上質'],
        imageLabel: '✨',
        affiliateUrl: 'https://example.com/affiliate/ce-st-2',
      },
    ],
    wave: [
      {
        id: 'ce-wv-1',
        itemName: 'Aラインシルクスカート',
        category: 'ボトムス',
        reason: 'ウェーブの柔らかさとクラシックの品格が融合した最高のフェミニン',
        point: 'フィットしたジャケットでXラインを作ると上流感UP',
        tags: ['Aライン', 'シルク', 'フェミニン'],
        imageLabel: '👑',
        affiliateUrl: 'https://example.com/affiliate/ce-wv-1',
      },
      {
        id: 'ce-wv-2',
        itemName: 'ドレープシフォンブラウス',
        category: 'トップス',
        reason: '柔らかなドレープがウェーブの曲線美を上品に引き立てる',
        point: 'タックインでウエストのラインを見せると◎',
        tags: ['ドレープ', 'シフォン', '上品'],
        imageLabel: '🌸',
        affiliateUrl: 'https://example.com/affiliate/ce-wv-2',
      },
    ],
    natural: [
      {
        id: 'ce-nt-1',
        itemName: 'オーバーサイズウールコート',
        category: 'アウター',
        reason: '骨格のフレーム感をゆったりテーラードで包み、風格ある大人の美意識を演出',
        point: 'シンプルなインナーでコートを主役に据えると◎',
        tags: ['ウール', 'オーバーサイズ', '大人'],
        imageLabel: '🏛️',
        affiliateUrl: 'https://example.com/affiliate/ce-nt-1',
      },
      {
        id: 'ce-nt-2',
        itemName: 'リネンワイドトラウザー',
        category: 'ボトムス',
        reason: '高品質素材とゆったりシルエットがナチュラル骨格の余裕感を演出',
        point: 'シャツをタックインしてYラインを意識して',
        tags: ['リネン', 'ワイド', 'クラシック'],
        imageLabel: '🎭',
        affiliateUrl: 'https://example.com/affiliate/ce-nt-2',
      },
    ],
  },

  FREE_SPIRIT: {
    straight: [
      {
        id: 'fs-st-1',
        itemName: 'ウエストマークボヘミアンワンピース',
        category: 'ワンピース',
        reason: 'メリハリ体型を活かしたウエストマークでボヘミアンをスタイリッシュにまとめる',
        point: 'ベルトを使ってウエストを強調するとより女性らしく',
        tags: ['ボヘミアン', 'ウエストマーク', '自然体'],
        imageLabel: '🌻',
        affiliateUrl: 'https://example.com/affiliate/fs-st-1',
      },
      {
        id: 'fs-st-2',
        itemName: 'スエードフリンジジャケット',
        category: 'アウター',
        reason: 'ボヘミアンの象徴ともいえるフリンジがストレートの直線ラインとのコントラストに',
        point: 'フィットした服の上に羽織ってボヘミアンをプラス',
        tags: ['スエード', 'フリンジ', 'ボヘミアン'],
        imageLabel: '🌵',
        affiliateUrl: 'https://example.com/affiliate/fs-st-2',
      },
    ],
    wave: [
      {
        id: 'fs-wv-1',
        itemName: 'ティアードフローラルスカート',
        category: 'ボトムス',
        reason: 'ウェーブの曲線美にフローする素材を組み合わせ、大地の女神のような自由さを',
        point: 'クロップトップでウエストを見せてバランスを取って',
        tags: ['ティアード', 'フローラル', 'ボヘミアン'],
        imageLabel: '🌺',
        affiliateUrl: 'https://example.com/affiliate/fs-wv-1',
      },
      {
        id: 'fs-wv-2',
        itemName: 'コットンクロップトップス',
        category: 'トップス',
        reason: 'フィット感でウェーブの曲線を活かしながら、ボヘミアンの軽やかさを演出',
        point: 'マキシスカートやティアードと合わせてバランス良く',
        tags: ['コットン', 'クロップド', 'ナチュラル'],
        imageLabel: '🌼',
        affiliateUrl: 'https://example.com/affiliate/fs-wv-2',
      },
    ],
    natural: [
      {
        id: 'fs-nt-1',
        itemName: 'リネンマキシワンピース',
        category: 'ワンピース',
        reason: '骨格のフレーム感とリネン・麻素材は抜群の相性。自然体ボヘミアンの完成形',
        point: 'レザーベルトをゆるく巻いてナチュラルにシルエットを作って',
        tags: ['リネン', 'マキシ', 'ボヘミアン'],
        imageLabel: '🌾',
        affiliateUrl: 'https://example.com/affiliate/fs-nt-1',
      },
      {
        id: 'fs-nt-2',
        itemName: 'ビッグシルエットレザージャケット',
        category: 'アウター',
        reason: '骨格の強さとレザーの存在感が合わさり、深みのある大人ボヘミアンに',
        point: 'ゆったりワンピースの上に羽織ってレイヤードを楽しんで',
        tags: ['レザー', 'オーバーサイズ', 'レイヤード'],
        imageLabel: '🏔️',
        affiliateUrl: 'https://example.com/affiliate/fs-nt-2',
      },
    ],
  },

  DARK_POET: {
    straight: [
      {
        id: 'dp-st-1',
        itemName: 'スリムブラックレザーパンツ',
        category: 'ボトムス',
        reason: 'メリハリボディにタイトなダークスタイルで、研ぎ澄まされた美意識を体現',
        point: 'タートルネックとの組み合わせで縦長Iラインを完成',
        tags: ['レザー', 'ブラック', 'タイト'],
        imageLabel: '🖤',
        affiliateUrl: 'https://example.com/affiliate/dp-st-1',
      },
      {
        id: 'dp-st-2',
        itemName: 'フィットレザージャケット',
        category: 'アウター',
        reason: 'メリハリシルエットを活かしたフィット感でダークポエットの孤高感を放つ',
        point: 'モノトーンでまとめて縦長ラインを意識して',
        tags: ['レザー', 'フィット', 'ダーク'],
        imageLabel: '🌑',
        affiliateUrl: 'https://example.com/affiliate/dp-st-2',
      },
    ],
    wave: [
      {
        id: 'dp-wv-1',
        itemName: 'ベルベットフィットワンピース',
        category: 'ワンピース',
        reason: '曲線美にゴシックの退廃美を纏わせ、唯一無二の闇のフェミニンを放つ',
        point: 'アクセサリーはシルバーのチョーカーでゴシック感を演出',
        tags: ['ベルベット', 'フィット', 'ゴシック'],
        imageLabel: '🌹',
        affiliateUrl: 'https://example.com/affiliate/dp-wv-1',
      },
      {
        id: 'dp-wv-2',
        itemName: 'コルセットトップス',
        category: 'トップス',
        reason: 'ウェーブの曲線美を最大限に引き立て、退廃的なフェミニンを完成させる',
        point: 'フレアスカートとの組み合わせで曲線美をさらに強調',
        tags: ['コルセット', 'フェミニン', '退廃的'],
        imageLabel: '🕷️',
        affiliateUrl: 'https://example.com/affiliate/dp-wv-2',
      },
    ],
    natural: [
      {
        id: 'dp-nt-1',
        itemName: 'ビッグシルエットウールコート',
        category: 'アウター',
        reason: '骨格の強さを活かしたビッグシルエットで、圧倒的な存在感のダークスタイル',
        point: 'モノトーンでまとめて全身をダークに統一',
        tags: ['ウール', 'ビッグシルエット', 'ダーク'],
        imageLabel: '🌙',
        affiliateUrl: 'https://example.com/affiliate/dp-nt-1',
      },
      {
        id: 'dp-nt-2',
        itemName: 'ワイドレイヤードパンツ',
        category: 'ボトムス',
        reason: '骨格の強さとワイドシルエットが合わさり、詩的な存在感を放つ',
        point: 'レイヤードシャツとの組み合わせでダークな深みを演出',
        tags: ['ワイド', 'レイヤード', 'ポエティック'],
        imageLabel: '🪶',
        affiliateUrl: 'https://example.com/affiliate/dp-nt-2',
      },
    ],
  },

  RETRO_WAVE: {
    straight: [
      {
        id: 'rw-st-1',
        itemName: 'ハイウエストフレアパンツ',
        category: 'ボトムス',
        reason: 'メリハリボディとハイウエストフレアの相性は最高。70sスタイルを完璧に再現',
        point: 'フィットしたトップスでXラインを作って',
        tags: ['ハイウエスト', 'フレア', 'レトロ'],
        imageLabel: '🕺',
        affiliateUrl: 'https://example.com/affiliate/rw-st-1',
      },
      {
        id: 'rw-st-2',
        itemName: 'クロップドデニムジャケット',
        category: 'アウター',
        reason: 'コンパクトなシルエットでメリハリを活かしながらヴィンテージ感を演出',
        point: 'ハイウエストパンツとのクロップド×ハイウエストコーデが◎',
        tags: ['デニム', 'クロップド', 'ヴィンテージ'],
        imageLabel: '🎸',
        affiliateUrl: 'https://example.com/affiliate/rw-st-2',
      },
    ],
    wave: [
      {
        id: 'rw-wv-1',
        itemName: 'フィットレトロニット',
        category: 'トップス',
        reason: 'ウェーブの曲線美にレトロカラーのフィットスタイルが最高にマッチ',
        point: 'ミニスカートやハイウエストパンツでウエストを強調して',
        tags: ['ニット', 'レトロ', 'フィット'],
        imageLabel: '🎨',
        affiliateUrl: 'https://example.com/affiliate/rw-wv-1',
      },
      {
        id: 'rw-wv-2',
        itemName: 'カラーブロックミニスカート',
        category: 'ボトムス',
        reason: 'ウェーブの脚ラインを活かしてレトロカラーでポップに',
        point: 'フィットしたトップスでウエストを強調するとバランス◎',
        tags: ['カラーブロック', 'ミニ', 'レトロ'],
        imageLabel: '🌈',
        affiliateUrl: 'https://example.com/affiliate/rw-wv-2',
      },
    ],
    natural: [
      {
        id: 'rw-nt-1',
        itemName: 'ビッグデニムジャケット',
        category: 'アウター',
        reason: 'フレーム感のある骨格にゆったりヴィンテージシルエットが絶妙にマッチ',
        point: 'シンプルなインナーで、ジャケットを主役に',
        tags: ['デニム', 'ビッグ', 'ヴィンテージ'],
        imageLabel: '🎵',
        affiliateUrl: 'https://example.com/affiliate/rw-nt-1',
      },
      {
        id: 'rw-nt-2',
        itemName: 'ワイドコーデュロイパンツ',
        category: 'ボトムス',
        reason: 'ナチュラル骨格のフレーム感を活かした70sヴィンテージシルエット',
        point: 'コンパクトなトップスでバランスを取るとスタイリッシュに',
        tags: ['コーデュロイ', 'ワイド', 'レトロ'],
        imageLabel: '🎺',
        affiliateUrl: 'https://example.com/affiliate/rw-nt-2',
      },
    ],
  },

  MINIMAL_SOUL: {
    straight: [
      {
        id: 'ms-st-1',
        itemName: 'カシミアリブニット',
        category: 'トップス',
        reason: '上質素材がメリハリボディと合わさり、究極の洗練されたミニマルスタイルに',
        point: 'スリムトラウザーとのIラインが完璧な組み合わせ',
        tags: ['カシミア', 'リブ', 'ミニマル'],
        imageLabel: '🤍',
        affiliateUrl: 'https://example.com/affiliate/ms-st-1',
      },
      {
        id: 'ms-st-2',
        itemName: 'タイトシルクスカート',
        category: 'ボトムス',
        reason: 'シルクの上質感とシンプルなシルエットで素材感だけで語るミニマリズム',
        point: 'モノトーンでまとめて洗練度を高めて',
        tags: ['シルク', 'タイト', 'ミニマル'],
        imageLabel: '⬜',
        affiliateUrl: 'https://example.com/affiliate/ms-st-2',
      },
    ],
    wave: [
      {
        id: 'ms-wv-1',
        itemName: 'フィットニット',
        category: 'トップス',
        reason: 'ウェーブの曲線美にフィットしたシンプルアイテムで上品なミニマルフェミニンを完成',
        point: 'シンプルなAラインスカートと合わせて余白のあるコーデに',
        tags: ['ニット', 'フィット', 'シンプル'],
        imageLabel: '🕊️',
        affiliateUrl: 'https://example.com/affiliate/ms-wv-1',
      },
      {
        id: 'ms-wv-2',
        itemName: 'マーメイドスカート',
        category: 'ボトムス',
        reason: 'シンプルなシルエットでウェーブの曲線美を最大限に引き立てる',
        point: 'トップスはタックインしてウエストのラインを出して',
        tags: ['マーメイド', 'フェミニン', 'ミニマル'],
        imageLabel: '🌊',
        affiliateUrl: 'https://example.com/affiliate/ms-wv-2',
      },
    ],
    natural: [
      {
        id: 'ms-nt-1',
        itemName: 'リネンゆったりシャツ',
        category: 'トップス',
        reason: '骨格のフレーム感を活かした、余白のある大人のミニマリズム',
        point: 'ワイドトラウザーとの組み合わせでYラインを意識して',
        tags: ['リネン', 'ゆったり', 'ミニマル'],
        imageLabel: '🌿',
        affiliateUrl: 'https://example.com/affiliate/ms-nt-1',
      },
      {
        id: 'ms-nt-2',
        itemName: 'ノーカラーシンプルコート',
        category: 'アウター',
        reason: '装飾のないシンプルなシルエットが骨格の美しさを最大限に引き出す',
        point: 'モノトーンの素材感でコーデ全体をまとめて',
        tags: ['ノーカラー', 'シンプル', 'ミニマル'],
        imageLabel: '⬛',
        affiliateUrl: 'https://example.com/affiliate/ms-nt-2',
      },
    ],
  },
}

export function getAffiliateItems(styleId: StyleId, bodyType: BodyType): AffiliateItem[] {
  return AFFILIATE_ITEMS[styleId][bodyType]
}
