import type { StyleId } from '@/lib/style-id/types'
import type { BodyType } from '@/lib/styleAdvice'

export type RecommendItem = {
  itemName: string
  reason: string
  point: string
  tags: string[]
  searchKeywords: string[]
  rakutenUrl?: string
  amazonUrl?: string
  usedUrl?: string
}

const RECOMMEND_ITEMS: Record<StyleId, Record<BodyType, RecommendItem[]>> = {
  COSMIC_REBEL: {
    straight: [
      {
        itemName: 'タイトメタリックパンツ',
        reason: 'メリハリシルエットを光沢素材で際立てて、宇宙的なシャープさを体現できる',
        point: 'タックインでIラインをはっきり出すと◎',
        tags: ['メタリック', 'タイト', 'シャープ', 'モード'],
        searchKeywords: ['メタリック スキニーパンツ レディース', '光沢 タイトパンツ 女性', 'シャイニー スリムパンツ'],
        rakutenUrl: 'https://example.com/rakuten/cr-st-1',
        amazonUrl: 'https://example.com/amazon/cr-st-1',
        usedUrl: 'https://example.com/used/cr-st-1',
      },
      {
        itemName: 'ストラクチャードジャケット',
        reason: '肩ラインをシャープに見せ、アバンギャルドな存在感を放てる',
        point: 'インナーはボディスーツなどタイトなものを合わせると◎',
        tags: ['ストラクチャード', 'アバンギャルド', 'モード'],
        searchKeywords: ['ストラクチャード ジャケット レディース', '肩パッド ジャケット モード', 'アバンギャルド テーラードジャケット'],
        rakutenUrl: 'https://example.com/rakuten/cr-st-2',
        amazonUrl: 'https://example.com/amazon/cr-st-2',
        usedUrl: 'https://example.com/used/cr-st-2',
      },
      {
        itemName: 'スリムレザーパンツ',
        reason: 'メリハリボディにレザーのエッジ感を加えてロックでかっこいいスタイルに',
        point: 'シンプルなトップスと合わせて素材感で魅せる',
        tags: ['レザー', 'スリム', 'エッジ', 'ロック'],
        searchKeywords: ['スリム レザーパンツ レディース', 'フェイクレザー タイトパンツ', 'レザー ボトムス ブラック 女性'],
        rakutenUrl: 'https://example.com/rakuten/cr-st-3',
        amazonUrl: 'https://example.com/amazon/cr-st-3',
        usedUrl: 'https://example.com/used/cr-st-3',
      },
    ],
    wave: [
      {
        itemName: 'フィットメタリックスカート',
        reason: '曲線美を活かしたフィット感でガーリーなSFスタイルを完成させる',
        point: 'クロップドトップスでウエストを強調して',
        tags: ['メタリック', 'フィット', 'フェミニン', 'SF'],
        searchKeywords: ['メタリック タイトスカート レディース', '光沢 フィットスカート 女性', 'シルバー スカート ミニ'],
        rakutenUrl: 'https://example.com/rakuten/cr-wv-1',
        amazonUrl: 'https://example.com/amazon/cr-wv-1',
        usedUrl: 'https://example.com/used/cr-wv-1',
      },
      {
        itemName: 'ボディコンワンピース',
        reason: 'カーブィなシルエットを最大限に引き立てるフィット感',
        point: 'アクセサリーはシルバー系でSF感を演出',
        tags: ['ボディコン', 'フィット', 'SF', 'フェミニン'],
        searchKeywords: ['ボディコン ワンピース レディース', 'タイト ワンピース フィット', 'スリム ワンピース 光沢'],
        rakutenUrl: 'https://example.com/rakuten/cr-wv-2',
        amazonUrl: 'https://example.com/amazon/cr-wv-2',
        usedUrl: 'https://example.com/used/cr-wv-2',
      },
      {
        itemName: 'ホルターネックトップス',
        reason: '肩を出すことでウェーブの柔らかさとSFのエッジを両立できる',
        point: 'ハイウエストボトムとの組み合わせでウエストをしっかり見せて',
        tags: ['ホルター', 'セクシー', 'フェミニン'],
        searchKeywords: ['ホルターネック トップス レディース', 'ホルター ブラトップ', 'バックレス トップス 女性'],
        rakutenUrl: 'https://example.com/rakuten/cr-wv-3',
        amazonUrl: 'https://example.com/amazon/cr-wv-3',
        usedUrl: 'https://example.com/used/cr-wv-3',
      },
    ],
    natural: [
      {
        itemName: 'ビッグシルエットコート',
        reason: 'フレーム感のある骨格にボリュームを重ねて、宇宙的な存在感を放てる',
        point: 'インナーをシンプルにしてコートを主役に据えると◎',
        tags: ['ビッグシルエット', 'コート', 'ボリューム'],
        searchKeywords: ['ビッグシルエット コート レディース', 'オーバーサイズ ロングコート 女性', 'ゆったり コート アウター'],
        rakutenUrl: 'https://example.com/rakuten/cr-nt-1',
        amazonUrl: 'https://example.com/amazon/cr-nt-1',
        usedUrl: 'https://example.com/used/cr-nt-1',
      },
      {
        itemName: 'オーバーサイズブルゾン',
        reason: '骨格の強さを活かしたボリュームアウターで、アバンギャルドな存在感を放つ',
        point: 'ワイドパンツとのYラインで骨格の強さを活かす',
        tags: ['オーバーサイズ', 'ブルゾン', 'レイヤード'],
        searchKeywords: ['オーバーサイズ ブルゾン レディース', 'ビッグ ブルゾン 女性', 'ゆったり スタジャン ジャケット'],
        rakutenUrl: 'https://example.com/rakuten/cr-nt-2',
        amazonUrl: 'https://example.com/amazon/cr-nt-2',
        usedUrl: 'https://example.com/used/cr-nt-2',
      },
      {
        itemName: 'ワイドレザーパンツ',
        reason: 'ナチュラル骨格のフレーム感とレザーの素材感が合わさり、圧倒的な存在感に',
        point: 'コンパクトなトップスとのYラインでバランスを取って',
        tags: ['レザー', 'ワイド', 'エッジ'],
        searchKeywords: ['ワイド レザーパンツ レディース', 'ワイドレッグ フェイクレザー ボトムス', 'レザー ワイドパンツ 黒'],
        rakutenUrl: 'https://example.com/rakuten/cr-nt-3',
        amazonUrl: 'https://example.com/amazon/cr-nt-3',
        usedUrl: 'https://example.com/used/cr-nt-3',
      },
    ],
  },

  SOFT_DREAMER: {
    straight: [
      {
        itemName: 'シルクサテンフィットワンピース',
        reason: 'メリハリボディに寄り添うシルクの光沢感で上品ドリーマーを演出',
        point: 'ベルトでウエストをさらに強調するとよりエレガントに',
        tags: ['シルク', 'サテン', 'フィット', 'エレガント'],
        searchKeywords: ['サテン フィットワンピース レディース', 'シルク調 ワンピース フォーマル', '光沢 タイトワンピース 女性'],
        rakutenUrl: 'https://example.com/rakuten/sd-st-1',
        amazonUrl: 'https://example.com/amazon/sd-st-1',
        usedUrl: 'https://example.com/used/sd-st-1',
      },
      {
        itemName: 'テーパードシフォンパンツ',
        reason: 'きれいなIラインでドリーマーの繊細さを表現できる',
        point: 'トップスをタックインしてスッキリしたシルエットに',
        tags: ['シフォン', 'テーパード', 'きれいめ'],
        searchKeywords: ['シフォン テーパードパンツ レディース', '透け感 フォーマルパンツ', 'きれいめ スリムパンツ 女性'],
        rakutenUrl: 'https://example.com/rakuten/sd-st-2',
        amazonUrl: 'https://example.com/amazon/sd-st-2',
        usedUrl: 'https://example.com/used/sd-st-2',
      },
      {
        itemName: 'シフォンブラウス',
        reason: '繊細な透け感がストレートの直線ラインに柔らかさをプラスする',
        point: 'タックインでウエストのメリハリを出して',
        tags: ['シフォン', 'ブラウス', '繊細', 'フェミニン'],
        searchKeywords: ['シフォン ブラウス レディース 透け感', 'フリル ブラウス きれいめ', 'エレガント ブラウス 女性'],
        rakutenUrl: 'https://example.com/rakuten/sd-st-3',
        amazonUrl: 'https://example.com/amazon/sd-st-3',
        usedUrl: 'https://example.com/used/sd-st-3',
      },
    ],
    wave: [
      {
        itemName: 'ティアードシフォンスカート',
        reason: '段々のフリルがウェーブの曲線美を引き立て、夢のような雰囲気に',
        point: 'フィットしたトップスでウエストのメリハリを出して',
        tags: ['シフォン', 'ティアード', 'フェミニン', 'ロマンティック'],
        searchKeywords: ['ティアードスカート シフォン レディース', 'フリル ロングスカート フェミニン', 'ボリューム スカート 透け感'],
        rakutenUrl: 'https://example.com/rakuten/sd-wv-1',
        amazonUrl: 'https://example.com/amazon/sd-wv-1',
        usedUrl: 'https://example.com/used/sd-wv-1',
      },
      {
        itemName: 'フリルブラウス',
        reason: 'ウェーブの柔らかさと相性抜群のフリルで最大限のフェミニンさを',
        point: 'スカートはシンプルなAラインで全体をバランス良く',
        tags: ['フリル', 'ガーリー', 'ロマンティック'],
        searchKeywords: ['フリル ブラウス レディース', 'ガーリー ブラウス フェミニン', 'フリル シャツ 女性 ロマンティック'],
        rakutenUrl: 'https://example.com/rakuten/sd-wv-2',
        amazonUrl: 'https://example.com/amazon/sd-wv-2',
        usedUrl: 'https://example.com/used/sd-wv-2',
      },
      {
        itemName: 'フィットアンドフレアワンピース',
        reason: 'ウェーブの曲線美とドリーマースタイルは最高の相性',
        point: 'ウエストがしっかりマークされているタイプを選んで',
        tags: ['フィットアンドフレア', 'フェミニン', 'ウエストマーク'],
        searchKeywords: ['フィットアンドフレア ワンピース レディース', 'ウエストマーク フレアワンピース', 'Aライン ワンピース フェミニン'],
        rakutenUrl: 'https://example.com/rakuten/sd-wv-3',
        amazonUrl: 'https://example.com/amazon/sd-wv-3',
        usedUrl: 'https://example.com/used/sd-wv-3',
      },
    ],
    natural: [
      {
        itemName: 'リネンマキシワンピース',
        reason: 'フレーム感のある骨格とリネンの自然な素材感が絶妙にマッチ',
        point: '腰にベルトをゆるく巻いてナチュラルにウエストを作ると◎',
        tags: ['リネン', 'マキシ', 'ナチュラル'],
        searchKeywords: ['リネン マキシワンピース レディース', '麻 ロングワンピース 春夏', 'ナチュラル ワンピース リゾート'],
        rakutenUrl: 'https://example.com/rakuten/sd-nt-1',
        amazonUrl: 'https://example.com/amazon/sd-nt-1',
        usedUrl: 'https://example.com/used/sd-nt-1',
      },
      {
        itemName: 'ゆったりシフォンブラウス',
        reason: 'ナチュラル骨格のフレーム感と透け感のある素材が自然体ドリーマーを完成させる',
        point: 'ロングスカートやワイドパンツと合わせてリラックス感を出して',
        tags: ['シフォン', 'ゆったり', 'ナチュラル'],
        searchKeywords: ['ゆったり シフォンブラウス レディース', 'ビッグ シルエット ブラウス 透け感', 'オーバーサイズ ブラウス 女性'],
        rakutenUrl: 'https://example.com/rakuten/sd-nt-2',
        amazonUrl: 'https://example.com/amazon/sd-nt-2',
        usedUrl: 'https://example.com/used/sd-nt-2',
      },
      {
        itemName: 'ロングカーディガン',
        reason: 'ゆったりとしたロング丈でフローイングなドリーマースタイルを完成',
        point: 'ワンピースやスカートの上に羽織ってレイヤードを楽しんで',
        tags: ['カーディガン', 'ロング', 'ゆったり', 'レイヤード'],
        searchKeywords: ['ロングカーディガン レディース', 'ロング丈 カーディガン ゆったり', 'マキシ丈 羽織り ニット'],
        rakutenUrl: 'https://example.com/rakuten/sd-nt-3',
        amazonUrl: 'https://example.com/amazon/sd-nt-3',
        usedUrl: 'https://example.com/used/sd-nt-3',
      },
    ],
  },

  URBAN_EDGE: {
    straight: [
      {
        itemName: 'スキニーデニム',
        reason: 'メリハリボディにスリムフィットで、ストリートをシャープに攻略',
        point: 'ロールアップして足首を見せるとよりスタイリッシュに',
        tags: ['デニム', 'スキニー', 'スリム', 'ストリート'],
        searchKeywords: ['スキニーデニム レディース', 'スリム ジーンズ 女性', 'タイト デニムパンツ ハイウエスト'],
        rakutenUrl: 'https://example.com/rakuten/ue-st-1',
        amazonUrl: 'https://example.com/amazon/ue-st-1',
        usedUrl: 'https://example.com/used/ue-st-1',
      },
      {
        itemName: 'クロップドグラフィックT',
        reason: 'コンパクトなシルエットでメリハリを活かしたストリートスタイルに',
        point: 'ハイウエストパンツとの組み合わせで脚長効果も',
        tags: ['クロップド', 'グラフィック', 'ストリート', 'カジュアル'],
        searchKeywords: ['クロップド グラフィックT レディース', 'ショート丈 Tシャツ プリント 女性', 'クロップトップ ストリート'],
        rakutenUrl: 'https://example.com/rakuten/ue-st-2',
        amazonUrl: 'https://example.com/amazon/ue-st-2',
        usedUrl: 'https://example.com/used/ue-st-2',
      },
      {
        itemName: 'テックパンツ',
        reason: 'スポーティーな素材感とスリムシルエットでアーバンエッジを演出',
        point: 'スニーカーとのセットで抜け感を出して',
        tags: ['テック', 'スポーティー', 'ストリート'],
        searchKeywords: ['テックパンツ レディース', 'ジョガーパンツ スポーティー 女性', 'ナイロン スリムパンツ ストリート'],
        rakutenUrl: 'https://example.com/rakuten/ue-st-3',
        amazonUrl: 'https://example.com/amazon/ue-st-3',
        usedUrl: 'https://example.com/used/ue-st-3',
      },
    ],
    wave: [
      {
        itemName: 'オーバーサイズT',
        reason: 'トップにボリュームを持たせてカーブィな下半身とのメリハリを演出',
        point: 'スキニーパンツやタイトスカートでバランスを取って',
        tags: ['オーバーサイズ', 'Tシャツ', 'カジュアル', 'ストリート'],
        searchKeywords: ['オーバーサイズ Tシャツ レディース', 'ビッグT ストリート 女性', 'ゆったり Tシャツ カジュアル'],
        rakutenUrl: 'https://example.com/rakuten/ue-wv-1',
        amazonUrl: 'https://example.com/amazon/ue-wv-1',
        usedUrl: 'https://example.com/used/ue-wv-1',
      },
      {
        itemName: 'バイカーショーツ',
        reason: 'ウェーブの曲線を活かしたフィット感でスポーティーかつフェミニンに',
        point: 'オーバーサイズトップスとのバランスが◎',
        tags: ['バイカー', 'ショーツ', 'スポーティー', 'フェミニン'],
        searchKeywords: ['バイカーショーツ レディース', 'サイクルショーツ スポーティー 女性', 'タイト ショートパンツ ストレッチ'],
        rakutenUrl: 'https://example.com/rakuten/ue-wv-2',
        amazonUrl: 'https://example.com/amazon/ue-wv-2',
        usedUrl: 'https://example.com/used/ue-wv-2',
      },
      {
        itemName: 'クロップドパーカー',
        reason: 'コンパクトな丈感でウェーブの重心を上げてスタイルアップ',
        point: 'ハイウエストボトムと合わせてタックインでさらに効果UP',
        tags: ['クロップド', 'パーカー', 'カジュアル'],
        searchKeywords: ['クロップド パーカー レディース', 'ショート丈 スウェット フーディー', 'ハーフ丈 パーカー 女性'],
        rakutenUrl: 'https://example.com/rakuten/ue-wv-3',
        amazonUrl: 'https://example.com/amazon/ue-wv-3',
        usedUrl: 'https://example.com/used/ue-wv-3',
      },
    ],
    natural: [
      {
        itemName: 'ビッグパーカー',
        reason: '骨格の強さを活かした圧倒的なボリューム感でストリートを支配',
        point: 'ワイドカーゴパンツと合わせてフルオーバーサイズに',
        tags: ['ビッグ', 'パーカー', 'オーバーサイズ', 'ストリート'],
        searchKeywords: ['ビッグシルエット パーカー レディース', 'オーバーサイズ フーディー 女性', 'ゆったり スウェット パーカー'],
        rakutenUrl: 'https://example.com/rakuten/ue-nt-1',
        amazonUrl: 'https://example.com/amazon/ue-nt-1',
        usedUrl: 'https://example.com/used/ue-nt-1',
      },
      {
        itemName: 'ワイドカーゴパンツ',
        reason: 'ゆったりとしたシルエットがナチュラル骨格のフレーム感を活かす',
        point: 'コンパクトなトップスとのYラインでバランスを取って',
        tags: ['カーゴ', 'ワイド', 'ユーティリティ', 'ストリート'],
        searchKeywords: ['ワイド カーゴパンツ レディース', 'カーゴ ワイドレッグ パンツ 女性', 'ユーティリティ パンツ ストリート'],
        rakutenUrl: 'https://example.com/rakuten/ue-nt-2',
        amazonUrl: 'https://example.com/amazon/ue-nt-2',
        usedUrl: 'https://example.com/used/ue-nt-2',
      },
      {
        itemName: 'ビッグシルエットMA-1',
        reason: '骨格の強さを活かした存在感のあるアウターでストリートを支配する',
        point: 'ワイドボトムと合わせてボリューミーに',
        tags: ['MA-1', 'オーバーサイズ', 'ミリタリー', 'ストリート'],
        searchKeywords: ['ビッグシルエット MA-1 レディース', 'オーバーサイズ フライトジャケット 女性', 'ゆったり ボンバージャケット'],
        rakutenUrl: 'https://example.com/rakuten/ue-nt-3',
        amazonUrl: 'https://example.com/amazon/ue-nt-3',
        usedUrl: 'https://example.com/used/ue-nt-3',
      },
    ],
  },

  CLASSIC_ELITE: {
    straight: [
      {
        itemName: 'テーラードジャケット',
        reason: 'メリハリ体型に王道テーラードで、エリートの品格を完璧に体現',
        point: 'インナーはシンプルなシャツやタートルネックで品格を保って',
        tags: ['テーラード', 'クラシック', '品格', 'エレガント'],
        searchKeywords: ['テーラードジャケット レディース 上品', 'フォーマル ジャケット 女性 きれいめ', 'スーツジャケット レディース'],
        rakutenUrl: 'https://example.com/rakuten/ce-st-1',
        amazonUrl: 'https://example.com/amazon/ce-st-1',
        usedUrl: 'https://example.com/used/ce-st-1',
      },
      {
        itemName: 'カシミアタートルネックニット',
        reason: '上質な素材感がメリハリシルエットをさらに洗練させる',
        point: 'スリムパンツと合わせてIラインを完成させて',
        tags: ['カシミア', 'タートルネック', '上質', 'ミニマル'],
        searchKeywords: ['カシミア タートルネック ニット レディース', 'ハイネック ニット 上質 女性', 'カシミヤ セーター 無地'],
        rakutenUrl: 'https://example.com/rakuten/ce-st-2',
        amazonUrl: 'https://example.com/amazon/ce-st-2',
        usedUrl: 'https://example.com/used/ce-st-2',
      },
      {
        itemName: 'フィットスカート',
        reason: 'Xラインを作り出すフィット感でクラシックエレガンスを完成',
        point: 'テーラードジャケットと合わせてスーツライクに',
        tags: ['フィット', 'スカート', 'クラシック', 'きれいめ'],
        searchKeywords: ['フィットスカート レディース きれいめ', 'タイト ひざ丈スカート オフィス', 'ペンシルスカート フォーマル'],
        rakutenUrl: 'https://example.com/rakuten/ce-st-3',
        amazonUrl: 'https://example.com/amazon/ce-st-3',
        usedUrl: 'https://example.com/used/ce-st-3',
      },
    ],
    wave: [
      {
        itemName: 'Aラインシルクスカート',
        reason: 'ウェーブの柔らかさとクラシックの品格が融合した最高のフェミニン',
        point: 'フィットしたジャケットでXラインを作ると上流感UP',
        tags: ['Aライン', 'シルク', 'フェミニン', 'エレガント'],
        searchKeywords: ['Aライン シルクスカート レディース', 'シルク調 フレアスカート フォーマル', 'エレガント スカート 上品'],
        rakutenUrl: 'https://example.com/rakuten/ce-wv-1',
        amazonUrl: 'https://example.com/amazon/ce-wv-1',
        usedUrl: 'https://example.com/used/ce-wv-1',
      },
      {
        itemName: 'ドレープシフォンブラウス',
        reason: '柔らかなドレープがウェーブの曲線美を上品に引き立てる',
        point: 'タックインでウエストのラインを見せると◎',
        tags: ['ドレープ', 'シフォン', '上品', 'エレガント'],
        searchKeywords: ['ドレープ シフォンブラウス レディース', 'エレガント ブラウス 透け感', 'フォーマル ブラウス 上品 女性'],
        rakutenUrl: 'https://example.com/rakuten/ce-wv-2',
        amazonUrl: 'https://example.com/amazon/ce-wv-2',
        usedUrl: 'https://example.com/used/ce-wv-2',
      },
      {
        itemName: 'フレアワンピース',
        reason: 'ウェーブの曲線美にフィット＆フレアのシルエットが理想のクラシックフェミニンを実現',
        point: 'ヒールで全体の重心を上げてよりエレガントに',
        tags: ['フレア', 'ワンピース', 'フェミニン', 'クラシック'],
        searchKeywords: ['フレアワンピース レディース エレガント', 'フォーマル ワンピース フレア 女性', 'きれいめ ワンピース Aライン'],
        rakutenUrl: 'https://example.com/rakuten/ce-wv-3',
        amazonUrl: 'https://example.com/amazon/ce-wv-3',
        usedUrl: 'https://example.com/used/ce-wv-3',
      },
    ],
    natural: [
      {
        itemName: 'オーバーサイズウールコート',
        reason: '骨格のフレーム感をゆったりテーラードで包み、風格ある大人の美意識を演出',
        point: 'シンプルなインナーでコートを主役に据えると◎',
        tags: ['ウール', 'オーバーサイズ', '大人', '上質'],
        searchKeywords: ['ウール オーバーサイズコート レディース', 'ゆったり ロングコート 上質 女性', 'ウールコート 大人 エレガント'],
        rakutenUrl: 'https://example.com/rakuten/ce-nt-1',
        amazonUrl: 'https://example.com/amazon/ce-nt-1',
        usedUrl: 'https://example.com/used/ce-nt-1',
      },
      {
        itemName: 'ワイドトラウザー',
        reason: '高品質素材とゆったりシルエットがナチュラル骨格の余裕感を演出',
        point: 'シャツをタックインしてYラインを意識して',
        tags: ['ワイド', 'トラウザー', 'クラシック', 'エレガント'],
        searchKeywords: ['ワイド トラウザーパンツ レディース', 'ワイドレッグ スラックス 上品 女性', 'フォーマル ワイドパンツ リネン'],
        rakutenUrl: 'https://example.com/rakuten/ce-nt-2',
        amazonUrl: 'https://example.com/amazon/ce-nt-2',
        usedUrl: 'https://example.com/used/ce-nt-2',
      },
      {
        itemName: 'メンズライクシャツ',
        reason: 'ナチュラル骨格のフレーム感とシャツの直線的なシルエットが絶妙にマッチ',
        point: 'パンツにタックインしてYラインを強調',
        tags: ['シャツ', 'メンズライク', 'クラシック', 'シンプル'],
        searchKeywords: ['メンズライク シャツ レディース', 'オーバーサイズ ドレスシャツ 女性', 'ビッグシルエット シャツ きれいめ'],
        rakutenUrl: 'https://example.com/rakuten/ce-nt-3',
        amazonUrl: 'https://example.com/amazon/ce-nt-3',
        usedUrl: 'https://example.com/used/ce-nt-3',
      },
    ],
  },

  FREE_SPIRIT: {
    straight: [
      {
        itemName: 'ウエストマークボヘミアンワンピース',
        reason: 'メリハリ体型を活かしたウエストマークでボヘミアンをスタイリッシュにまとめる',
        point: 'ベルトを使ってウエストをさらに強調するとより女性らしく',
        tags: ['ボヘミアン', 'ウエストマーク', '自然体', 'フェミニン'],
        searchKeywords: ['ボヘミアン ワンピース ウエストマーク レディース', 'エスニック ワンピース ベルト 女性', 'ボヘミアン ワンピース 春夏'],
        rakutenUrl: 'https://example.com/rakuten/fs-st-1',
        amazonUrl: 'https://example.com/amazon/fs-st-1',
        usedUrl: 'https://example.com/used/fs-st-1',
      },
      {
        itemName: 'フィットチュニック',
        reason: 'メリハリシルエットにフィットしたチュニックでボヘミアンの軽やかさを表現',
        point: 'スキニーやタイトスカートと合わせてシルエットにメリハリを',
        tags: ['チュニック', 'フィット', 'ナチュラル'],
        searchKeywords: ['フィット チュニック レディース', 'ナチュラル チュニック 女性', 'エスニック チュニック ワンピース'],
        rakutenUrl: 'https://example.com/rakuten/fs-st-2',
        amazonUrl: 'https://example.com/amazon/fs-st-2',
        usedUrl: 'https://example.com/used/fs-st-2',
      },
      {
        itemName: '刺繍ブラウス',
        reason: 'ボヘミアンの象徴である刺繍がストレートのシルエットに個性をプラス',
        point: 'タックインでウエストをしっかり見せて',
        tags: ['刺繍', 'ブラウス', 'ボヘミアン', 'エスニック'],
        searchKeywords: ['刺繍 ブラウス レディース', 'エスニック 刺繍 シャツ 女性', 'ボヘミアン ブラウス 刺繍 花柄'],
        rakutenUrl: 'https://example.com/rakuten/fs-st-3',
        amazonUrl: 'https://example.com/amazon/fs-st-3',
        usedUrl: 'https://example.com/used/fs-st-3',
      },
    ],
    wave: [
      {
        itemName: 'ティアードフローラルスカート',
        reason: 'ウェーブの曲線美にフローする素材を組み合わせ、大地の女神のような自由さを',
        point: 'クロップトップでウエストを見せてバランスを取って',
        tags: ['ティアード', 'フローラル', 'ボヘミアン', 'フェミニン'],
        searchKeywords: ['ティアードスカート フローラル レディース', 'ボヘミアン 花柄スカート ロング', 'エスニック スカート フレア 女性'],
        rakutenUrl: 'https://example.com/rakuten/fs-wv-1',
        amazonUrl: 'https://example.com/amazon/fs-wv-1',
        usedUrl: 'https://example.com/used/fs-wv-1',
      },
      {
        itemName: 'フローラルワンピース',
        reason: 'ウェーブの曲線美と花柄の組み合わせはボヘミアンフェミニンの王道',
        point: 'ウエストにベルトを追加してシルエットに変化をつけると◎',
        tags: ['フローラル', 'ワンピース', 'ボヘミアン', 'ロマンティック'],
        searchKeywords: ['フローラル ボヘミアン ワンピース レディース', '花柄 ロングワンピース 女性 ナチュラル', 'エスニック 花柄ワンピース'],
        rakutenUrl: 'https://example.com/rakuten/fs-wv-2',
        amazonUrl: 'https://example.com/amazon/fs-wv-2',
        usedUrl: 'https://example.com/used/fs-wv-2',
      },
      {
        itemName: 'クロップトップス',
        reason: 'フィット感でウェーブの曲線を活かしながら、ボヘミアンの軽やかさを演出',
        point: 'マキシスカートやティアードと合わせてバランス良く',
        tags: ['クロップド', 'トップス', 'ナチュラル', 'ボヘミアン'],
        searchKeywords: ['クロップトップス ナチュラル レディース', 'クロップ トップス ボヘミアン 女性', 'ショート丈 トップス 刺繍'],
        rakutenUrl: 'https://example.com/rakuten/fs-wv-3',
        amazonUrl: 'https://example.com/amazon/fs-wv-3',
        usedUrl: 'https://example.com/used/fs-wv-3',
      },
    ],
    natural: [
      {
        itemName: 'リネンワンピース',
        reason: '骨格のフレーム感とリネン・麻素材は抜群の相性。自然体ボヘミアンの完成形',
        point: 'レザーベルトをゆるく巻いてナチュラルにシルエットを作って',
        tags: ['リネン', 'ワンピース', 'ボヘミアン', 'ナチュラル'],
        searchKeywords: ['リネン ワンピース ボヘミアン レディース', '麻 ワンピース ナチュラル 女性', 'リネン ロングワンピース 春夏'],
        rakutenUrl: 'https://example.com/rakuten/fs-nt-1',
        amazonUrl: 'https://example.com/amazon/fs-nt-1',
        usedUrl: 'https://example.com/used/fs-nt-1',
      },
      {
        itemName: 'ロングベスト',
        reason: 'フレーム感のある骨格に縦のラインを強調してボヘミアンな装いに',
        point: 'ロングワンピースやワイドパンツの上から羽織って奥行きを出して',
        tags: ['ロング', 'ベスト', 'レイヤード', 'ボヘミアン'],
        searchKeywords: ['ロングベスト ボヘミアン レディース', 'ロング丈 ジレ ナチュラル 女性', 'エスニック ベスト ロング'],
        rakutenUrl: 'https://example.com/rakuten/fs-nt-2',
        amazonUrl: 'https://example.com/amazon/fs-nt-2',
        usedUrl: 'https://example.com/used/fs-nt-2',
      },
      {
        itemName: 'ワイドリネンパンツ',
        reason: 'ナチュラル骨格のフレーム感とリネンのゆったり感が自然体ボヘミアンを体現',
        point: 'シンプルなトップスと合わせてパンツを主役に',
        tags: ['リネン', 'ワイド', 'ナチュラル', 'ゆったり'],
        searchKeywords: ['ワイド リネンパンツ レディース', '麻 ワイドパンツ 女性 ナチュラル', 'リネン ガウチョパンツ 春夏'],
        rakutenUrl: 'https://example.com/rakuten/fs-nt-3',
        amazonUrl: 'https://example.com/amazon/fs-nt-3',
        usedUrl: 'https://example.com/used/fs-nt-3',
      },
    ],
  },

  DARK_POET: {
    straight: [
      {
        itemName: 'スリムブラックパンツ',
        reason: 'メリハリボディにタイトなダークスタイルで、研ぎ澄まされた美意識を体現',
        point: 'タートルネックとの組み合わせで縦長Iラインを完成',
        tags: ['ブラック', 'スリム', 'タイト', 'ダーク'],
        searchKeywords: ['スリム ブラックパンツ レディース', '黒 タイトパンツ 女性', 'ブラック スキニーパンツ モード'],
        rakutenUrl: 'https://example.com/rakuten/dp-st-1',
        amazonUrl: 'https://example.com/amazon/dp-st-1',
        usedUrl: 'https://example.com/used/dp-st-1',
      },
      {
        itemName: 'フィットレザージャケット',
        reason: 'メリハリシルエットを活かしたフィット感でダークポエットの孤高感を放つ',
        point: 'モノトーンでまとめて縦長ラインを意識して',
        tags: ['レザー', 'フィット', 'ダーク', 'エッジ'],
        searchKeywords: ['フィット レザージャケット レディース', 'ライダースジャケット 女性 スリム', 'レザー ジャケット ブラック フィット'],
        rakutenUrl: 'https://example.com/rakuten/dp-st-2',
        amazonUrl: 'https://example.com/amazon/dp-st-2',
        usedUrl: 'https://example.com/used/dp-st-2',
      },
      {
        itemName: 'タートルネックニット',
        reason: '首元を覆うハイネックが知的でダークな雰囲気を醸し出す',
        point: 'モノトーンコーデの軸として使い、他を引き立てて',
        tags: ['タートルネック', 'ニット', 'モード', 'ダーク'],
        searchKeywords: ['タートルネック ニット レディース ブラック', 'ハイネック ニット 黒 女性', 'モード タートル セーター'],
        rakutenUrl: 'https://example.com/rakuten/dp-st-3',
        amazonUrl: 'https://example.com/amazon/dp-st-3',
        usedUrl: 'https://example.com/used/dp-st-3',
      },
    ],
    wave: [
      {
        itemName: 'ベルベットフィットワンピース',
        reason: '曲線美にゴシックの退廃美を纏わせ、唯一無二の闇のフェミニンを放つ',
        point: 'アクセサリーはシルバーのチョーカーでゴシック感を演出',
        tags: ['ベルベット', 'フィット', 'ゴシック', 'ダーク'],
        searchKeywords: ['ベルベット フィットワンピース レディース', 'ゴシック ワンピース 黒 女性', 'ベルベット ドレス フィット'],
        rakutenUrl: 'https://example.com/rakuten/dp-wv-1',
        amazonUrl: 'https://example.com/amazon/dp-wv-1',
        usedUrl: 'https://example.com/used/dp-wv-1',
      },
      {
        itemName: 'コルセットトップス',
        reason: 'ウェーブの曲線美を最大限に引き立て、退廃的なフェミニンを完成させる',
        point: 'フレアスカートとの組み合わせで曲線美をさらに強調',
        tags: ['コルセット', 'フェミニン', '退廃的', 'ゴシック'],
        searchKeywords: ['コルセット トップス レディース', 'コルセット デザイン トップス 女性', 'ビスチェ コルセット ブラック'],
        rakutenUrl: 'https://example.com/rakuten/dp-wv-2',
        amazonUrl: 'https://example.com/amazon/dp-wv-2',
        usedUrl: 'https://example.com/used/dp-wv-2',
      },
      {
        itemName: 'レースブラウス',
        reason: '繊細なレースがウェーブの柔らかさとゴシックの退廃美を絶妙に融合させる',
        point: 'ブラックのタイトボトムと合わせてダークフェミニンを完成',
        tags: ['レース', 'ブラウス', 'ゴシック', 'フェミニン'],
        searchKeywords: ['レース ブラウス ブラック レディース', 'ゴシック レース シャツ 女性', '黒 レースブラウス ダーク'],
        rakutenUrl: 'https://example.com/rakuten/dp-wv-3',
        amazonUrl: 'https://example.com/amazon/dp-wv-3',
        usedUrl: 'https://example.com/used/dp-wv-3',
      },
    ],
    natural: [
      {
        itemName: 'ビッグシルエットウールコート',
        reason: '骨格の強さを活かしたビッグシルエットで、圧倒的な存在感のダークスタイル',
        point: 'モノトーンでまとめて全身をダークに統一',
        tags: ['ウール', 'ビッグシルエット', 'ダーク', 'コート'],
        searchKeywords: ['ビッグシルエット コート ブラック レディース', 'オーバーサイズ ウールコート 黒 女性', 'ゆったり ロングコート ダーク'],
        rakutenUrl: 'https://example.com/rakuten/dp-nt-1',
        amazonUrl: 'https://example.com/amazon/dp-nt-1',
        usedUrl: 'https://example.com/used/dp-nt-1',
      },
      {
        itemName: 'ワイドパンツ ブラック',
        reason: 'ナチュラル骨格のフレーム感とワイドシルエットが合わさり、詩的な存在感を放つ',
        point: 'レイヤードシャツとの組み合わせでダークな深みを演出',
        tags: ['ワイド', 'ブラック', 'ダーク', 'モード'],
        searchKeywords: ['ワイドパンツ ブラック レディース', 'ワイドレッグ 黒 パンツ 女性', 'ダーク ワイドパンツ モード'],
        rakutenUrl: 'https://example.com/rakuten/dp-nt-2',
        amazonUrl: 'https://example.com/amazon/dp-nt-2',
        usedUrl: 'https://example.com/used/dp-nt-2',
      },
      {
        itemName: 'ロングカーディガン ブラック',
        reason: 'ゆったりとしたロング丈がナチュラル骨格のフレーム感を包み、詩的なシルエットに',
        point: 'タートルネックやレースアイテムの上に羽織ってレイヤードを',
        tags: ['カーディガン', 'ロング', 'ブラック', 'レイヤード'],
        searchKeywords: ['ロングカーディガン ブラック レディース', '黒 ロング羽織り ニット 女性', 'ダーク ロングカーディガン モード'],
        rakutenUrl: 'https://example.com/rakuten/dp-nt-3',
        amazonUrl: 'https://example.com/amazon/dp-nt-3',
        usedUrl: 'https://example.com/used/dp-nt-3',
      },
    ],
  },

  RETRO_WAVE: {
    straight: [
      {
        itemName: 'ハイウエストスキニーデニム',
        reason: 'メリハリボディとハイウエストスキニーの相性は最高。70sスタイルを完璧に再現',
        point: 'フィットしたトップスでXラインを作って',
        tags: ['ハイウエスト', 'スキニー', 'デニム', 'レトロ'],
        searchKeywords: ['ハイウエスト スキニーデニム レディース', 'ハイライズ スキニージーンズ 女性', 'ヴィンテージ風 ハイウエスト デニム'],
        rakutenUrl: 'https://example.com/rakuten/rw-st-1',
        amazonUrl: 'https://example.com/amazon/rw-st-1',
        usedUrl: 'https://example.com/used/rw-st-1',
      },
      {
        itemName: 'クロップドデニムジャケット',
        reason: 'コンパクトなシルエットでメリハリを活かしながらヴィンテージ感を演出',
        point: 'ハイウエストパンツとのクロップド×ハイウエストコーデが◎',
        tags: ['デニム', 'クロップド', 'ヴィンテージ', 'レトロ'],
        searchKeywords: ['クロップド デニムジャケット レディース', 'ショート丈 Gジャン 女性', 'ヴィンテージ デニムジャケット レトロ'],
        rakutenUrl: 'https://example.com/rakuten/rw-st-2',
        amazonUrl: 'https://example.com/amazon/rw-st-2',
        usedUrl: 'https://example.com/used/rw-st-2',
      },
      {
        itemName: 'フレアパンツ ハイウエスト',
        reason: 'ハイウエストのフレアシルエットがメリハリボディをさらに引き立てる',
        point: 'ウエストがしっかり入るフィット感のものを選んで',
        tags: ['フレア', 'ハイウエスト', 'レトロ', '70s'],
        searchKeywords: ['ハイウエスト フレアパンツ レディース', 'ベルボトム パンツ 女性 レトロ', '70s フレアパンツ ヴィンテージ'],
        rakutenUrl: 'https://example.com/rakuten/rw-st-3',
        amazonUrl: 'https://example.com/amazon/rw-st-3',
        usedUrl: 'https://example.com/used/rw-st-3',
      },
    ],
    wave: [
      {
        itemName: 'フィットセーター レトロカラー',
        reason: 'ウェーブの曲線美にレトロカラーのフィットスタイルが最高にマッチ',
        point: 'ミニスカートやハイウエストパンツでウエストを強調して',
        tags: ['セーター', 'レトロ', 'フィット', 'カラフル'],
        searchKeywords: ['フィット セーター レトロ レディース', 'ニット プルオーバー レトロカラー 女性', 'ヴィンテージ風 セーター カラーニット'],
        rakutenUrl: 'https://example.com/rakuten/rw-wv-1',
        amazonUrl: 'https://example.com/amazon/rw-wv-1',
        usedUrl: 'https://example.com/used/rw-wv-1',
      },
      {
        itemName: 'カラーブロックミニスカート',
        reason: 'ウェーブの脚ラインを活かしてレトロカラーでポップに',
        point: 'フィットしたトップスでウエストを強調するとバランス◎',
        tags: ['カラーブロック', 'ミニ', 'レトロ', 'ポップ'],
        searchKeywords: ['カラーブロック ミニスカート レディース', 'レトロ ミニスカート カラー 女性', 'ポップ スカート ヴィンテージ風'],
        rakutenUrl: 'https://example.com/rakuten/rw-wv-2',
        amazonUrl: 'https://example.com/amazon/rw-wv-2',
        usedUrl: 'https://example.com/used/rw-wv-2',
      },
      {
        itemName: 'ハイウエストパンツ レトロ',
        reason: 'ウェーブの上半身の小ささを活かしてハイウエストで重心を上げるスタイル',
        point: 'フィットしたトップスのタックインで重心をさらに高く',
        tags: ['ハイウエスト', 'レトロ', 'パンツ', 'ヴィンテージ'],
        searchKeywords: ['ハイウエストパンツ レトロ レディース', 'ヴィンテージ風 ハイライズパンツ 女性', 'レトロ スラックス ハイウエスト'],
        rakutenUrl: 'https://example.com/rakuten/rw-wv-3',
        amazonUrl: 'https://example.com/amazon/rw-wv-3',
        usedUrl: 'https://example.com/used/rw-wv-3',
      },
    ],
    natural: [
      {
        itemName: 'ビッグデニムジャケット',
        reason: 'フレーム感のある骨格にゆったりヴィンテージシルエットが絶妙にマッチ',
        point: 'シンプルなインナーで、ジャケットを主役に',
        tags: ['デニム', 'ビッグシルエット', 'ヴィンテージ', 'レトロ'],
        searchKeywords: ['ビッグシルエット デニムジャケット レディース', 'オーバーサイズ Gジャン 女性', 'ゆったり デニムジャケット ヴィンテージ'],
        rakutenUrl: 'https://example.com/rakuten/rw-nt-1',
        amazonUrl: 'https://example.com/amazon/rw-nt-1',
        usedUrl: 'https://example.com/used/rw-nt-1',
      },
      {
        itemName: 'ワイドコーデュロイパンツ',
        reason: 'ナチュラル骨格のフレーム感を活かした70sヴィンテージシルエット',
        point: 'コンパクトなトップスでバランスを取るとスタイリッシュに',
        tags: ['コーデュロイ', 'ワイド', 'レトロ', 'ヴィンテージ'],
        searchKeywords: ['ワイド コーデュロイパンツ レディース', 'コーデュロイ ワイドレッグ 女性 レトロ', 'ヴィンテージ風 コーデュロイ パンツ'],
        rakutenUrl: 'https://example.com/rakuten/rw-nt-2',
        amazonUrl: 'https://example.com/amazon/rw-nt-2',
        usedUrl: 'https://example.com/used/rw-nt-2',
      },
      {
        itemName: 'フランネルシャツ オーバーサイズ',
        reason: '骨格のフレーム感とフランネルの素朴な素材感がレトロな雰囲気を醸し出す',
        point: 'ウエストを結んだりタックインでシルエットに変化を',
        tags: ['フランネル', 'シャツ', 'オーバーサイズ', 'レトロ'],
        searchKeywords: ['フランネルシャツ オーバーサイズ レディース', 'ネルシャツ ビッグ 女性 レトロ', 'チェック シャツ ゆったり ヴィンテージ'],
        rakutenUrl: 'https://example.com/rakuten/rw-nt-3',
        amazonUrl: 'https://example.com/amazon/rw-nt-3',
        usedUrl: 'https://example.com/used/rw-nt-3',
      },
    ],
  },

  MINIMAL_SOUL: {
    straight: [
      {
        itemName: 'スリムトラウザー',
        reason: 'メリハリ体型×シンプルシルエットは無敵の組み合わせ',
        point: 'ハリのある素材のものを選んで、シルエットのきれいさを際立てて',
        tags: ['スリム', 'トラウザー', 'ミニマル', 'きれいめ'],
        searchKeywords: ['スリム トラウザーパンツ レディース', 'スリムスラックス きれいめ 女性', 'シンプル スリムパンツ ミニマル'],
        rakutenUrl: 'https://example.com/rakuten/ms-st-1',
        amazonUrl: 'https://example.com/amazon/ms-st-1',
        usedUrl: 'https://example.com/used/ms-st-1',
      },
      {
        itemName: 'カシミアリブニット',
        reason: '上質素材がメリハリボディと合わさり、究極の洗練されたミニマルスタイルに',
        point: 'スリムトラウザーとのIラインが完璧な組み合わせ',
        tags: ['カシミア', 'リブ', 'ミニマル', '上質'],
        searchKeywords: ['カシミア リブニット レディース', 'カシミヤ ニット 無地 上質 女性', 'リブ セーター ミニマル'],
        rakutenUrl: 'https://example.com/rakuten/ms-st-2',
        amazonUrl: 'https://example.com/amazon/ms-st-2',
        usedUrl: 'https://example.com/used/ms-st-2',
      },
      {
        itemName: 'Vネックシャツ 上質',
        reason: 'シンプルなVネックがメリハリシルエットを際立てるミニマルコーデの主役',
        point: 'スリムパンツとのIラインでモノトーンにまとめると◎',
        tags: ['Vネック', 'シャツ', 'ミニマル', 'シンプル'],
        searchKeywords: ['Vネック シャツ レディース シンプル', '上質 Vネック トップス 女性 ミニマル', 'コットン Vネック 無地 レディース'],
        rakutenUrl: 'https://example.com/rakuten/ms-st-3',
        amazonUrl: 'https://example.com/amazon/ms-st-3',
        usedUrl: 'https://example.com/used/ms-st-3',
      },
    ],
    wave: [
      {
        itemName: 'フィットニット シンプル',
        reason: 'ウェーブの曲線美にフィットしたシンプルアイテムで上品なミニマルフェミニンを完成',
        point: 'シンプルなAラインスカートと合わせて余白のあるコーデに',
        tags: ['ニット', 'フィット', 'シンプル', 'ミニマル'],
        searchKeywords: ['フィット ニット レディース シンプル', 'スリム セーター 無地 女性 ミニマル', 'コンパクト ニット フィット'],
        rakutenUrl: 'https://example.com/rakuten/ms-wv-1',
        amazonUrl: 'https://example.com/amazon/ms-wv-1',
        usedUrl: 'https://example.com/used/ms-wv-1',
      },
      {
        itemName: 'シンプルAラインスカート',
        reason: 'ウェーブのフレアシルエットとミニマルなデザインが上品に調和する',
        point: 'フィットしたトップスでウエストを強調',
        tags: ['Aライン', 'シンプル', 'ミニマル', 'フェミニン'],
        searchKeywords: ['Aライン スカート レディース シンプル', 'シンプル フレアスカート 無地 女性', 'ミニマル スカート きれいめ'],
        rakutenUrl: 'https://example.com/rakuten/ms-wv-2',
        amazonUrl: 'https://example.com/amazon/ms-wv-2',
        usedUrl: 'https://example.com/used/ms-wv-2',
      },
      {
        itemName: 'マーメイドスカート',
        reason: 'シンプルなシルエットでウェーブの曲線美を最大限に引き立てる',
        point: 'トップスはタックインしてウエストのラインを出して',
        tags: ['マーメイド', 'フェミニン', 'ミニマル', 'フィット'],
        searchKeywords: ['マーメイドスカート レディース ミニマル', 'マーメイド ロングスカート 無地 女性', 'フィッシュテール スカート シンプル'],
        rakutenUrl: 'https://example.com/rakuten/ms-wv-3',
        amazonUrl: 'https://example.com/amazon/ms-wv-3',
        usedUrl: 'https://example.com/used/ms-wv-3',
      },
    ],
    natural: [
      {
        itemName: 'リネンゆったりシャツ',
        reason: '骨格のフレーム感を活かした、余白のある大人のミニマリズム',
        point: 'ワイドトラウザーとの組み合わせでYラインを意識して',
        tags: ['リネン', 'ゆったり', 'ミニマル', 'ナチュラル'],
        searchKeywords: ['リネン シャツ ゆったり レディース', '麻 ビッグシャツ 女性 ミニマル', 'リネン オーバーサイズシャツ 無地'],
        rakutenUrl: 'https://example.com/rakuten/ms-nt-1',
        amazonUrl: 'https://example.com/amazon/ms-nt-1',
        usedUrl: 'https://example.com/used/ms-nt-1',
      },
      {
        itemName: 'ワイドトラウザー 上質',
        reason: 'ナチュラル骨格のフレーム感を活かした、余白のある大人のシルエット',
        point: 'シャツをタックインしてYラインを意識して',
        tags: ['ワイド', 'トラウザー', 'ミニマル', '上質'],
        searchKeywords: ['ワイドトラウザー 上質 レディース', 'ワイドスラックス 上品 女性 ミニマル', 'ゆったり パンツ 上質 無地'],
        rakutenUrl: 'https://example.com/rakuten/ms-nt-2',
        amazonUrl: 'https://example.com/amazon/ms-nt-2',
        usedUrl: 'https://example.com/used/ms-nt-2',
      },
      {
        itemName: 'ノーカラーシンプルコート',
        reason: '装飾のないシンプルなシルエットが骨格の美しさを最大限に引き出す',
        point: 'モノトーンの素材感でコーデ全体をまとめて',
        tags: ['ノーカラー', 'コート', 'シンプル', 'ミニマル'],
        searchKeywords: ['ノーカラーコート レディース シンプル', '襟なし コート 女性 ミニマル', 'シンプル ロングコート ノーカラー'],
        rakutenUrl: 'https://example.com/rakuten/ms-nt-3',
        amazonUrl: 'https://example.com/amazon/ms-nt-3',
        usedUrl: 'https://example.com/used/ms-nt-3',
      },
    ],
  },
}

export function getRecommendItems(styleId: StyleId, bodyType: BodyType): RecommendItem[] {
  return RECOMMEND_ITEMS[styleId][bodyType]
}
